version: '3.8'
services:
  library-service:
    container_name: library-service
    image: library-service:1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - db-service
    environment:
      - SERVER_PORT=9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-service/library_db

  db-service:
    #    image: postgres:14.7-alpine
    container_name: db-service
    image: db-service:1.0
    build:
      context: src/main/resources/db
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library_db
    ports:
      - "15432:5432"
    restart: unless-stopped