#Spring Properties
spring:
  #Data Source Properties
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/library_db
    username: postgres
    password: postgres

  #JPA Properties
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: TRUE
        show_sql: TRUE
        hbm2ddl:
          auto: update
#Disable the default loggers
#Show SQL executed with parameter bindings
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor: TRACE
    blog: WARN
#Server port
server:
  port: 5000

#cont
app:
  default:
    pass: secret


